# Generated by Django 4.2.8 on 2023-12-07 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product_Crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product_detail',
            table='product_details',
        ),
    ]
